version: "3.7"

networks:
  default:
    external: true
    name: aline

services:
  bank-service:
    build: .
    image: aline/bank-microservice
    env_file:
      - .env
    ports:
      - 8083:8083
